### ISSUE TITLE
TV Show Covers Cropped

### ISSUE THREAD

**Issue by xzener** [Ghawken/FrontView#2] opened 2016-08-06 18:43 UTC
Glenn,

The Movie covers display perfectly. Although, if using a different cover using CoverArt (ClearCase for example) the covers are being cropped incorrectly. This is an issue in my TV Shows view, in case that helps narrow the problem down.

Here is a picture of the example in CoverArt...
![capture](https://cloud.githubusercontent.com/assets/3745669/17458584/7e55e3d0-5bca-11e6-90d2-180e138f66a7.PNG)

Here is the cover being cropped incorrectly in FV+...
![capture2](https://cloud.githubusercontent.com/assets/3745669/17458595/dab2d534-5bca-11e6-9844-162d8b76fd22.PNG)

**Comment by Ghawken** [comment] 2016-08-06 20:54
The issue is that it seems cover artwork adding for Emby  changes the aspect ratio and resulting size of the image files Emby serves - making it a bit hard to be compatible with all.  My testing involved Tv coverart (up the top blue Tv series one) which works okay.  Your case shown obviously makes the images that much wider.

If I shrink the image on smallest dimension you get a reasonable amount of black space which doesn't look so good in cover flow.

This aspect is skin able as I discussed in the thread and posted - two width and height cover flow settings to change.  Don't really fancy having a separate skin for ever coverart possibility (particularly considering the rotation setting which would mean lots of different sized files).

Glenn

**Comment by Ghawken** [comment] 2016-08-06 21:09
Coverart on Emby has a setting 

Use "original art aspect ratio"
Suspect we need to Check this to enable best compatibility with multiple options.

May still need some minor fine tuning with this enabled which will look at.

**Comment by Ghawken** [comment] 2016-08-06 22:18
My above comment - completely buggers up the display of the coverflow.

Some of the coverart pulled seem to be old aspect and some seem to be new - checking now whether difference in way FV+ pulls - or if just time for Emby Server to regenerate and catch up.

Either way - the default skins now are wrong - will move towards the above option as should mean all is right for all Emby Cover treatments - but will need some Skin changes and resizing which am working on now.

Glenn

**Comment by xzener** [comment] 2016-08-07 04:28
Well done Glenn. Keep up the great work.

**Comment by Ghawken** [comment] 2016-08-07 12:36
Closing as now fixed - will post build soon. (V1.161)

Need to select 'use original aspect ratio' on Emby coverart & regenerate all images/cache.

New build has correct movie, tv cover flow and new versions of movies details screen for Emby.

  The Xaml is quite time consuming to edit as the very large xaml file isn't editable easily in editor - more a question of changing one aspect and trialling.   The other major aspect is trying to support multiple screen sizes - what works in 1024x768 doesn't really in 800x480.   Just finishing that off which is taking time.  (No real bells and whistles on movies details screen just better arranged)

Glenn

**Closed as completed by Ghawken** 2016-08-07 12:36 UTC
